### ISSUE TITLE
Use only 1 UserParameter

### ISSUE THREAD

**Issue by canepan** [m4ce/zabbix-bind#1]
Wouldn't be it easier to use only 1 UserParameter, with $1 $2 $3 passed from the template?

**Comment by m4ce** [comment]
Hi,

it is easier indeed but I find it less readable. It's really just a personal preference.

I sort follow the Zabbix way of naming items (https://www.zabbix.com/documentation/2.2/manual/config/items/itemtypes/zabbix_agent).

If having X items rather than one make things difficult for you, I suggest you look into distributing your user parameters configuration via some cfg management tool.

Regards,
Matteo
